{
 "title": "Flux Cluster Stats",
 "tags": [ "flux" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "operator_namespace",
    "query": {
     "query": "label_values(gotk_reconcile_condition, namespace)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(gotk_reconcile_condition, exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_reconcile_condition{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",type=\"Ready\",status=\"True\",kind=~\"Kustomization|HelmRelease\"})\n-\nsum(gotk_reconcile_condition{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",type=\"Ready\",status=\"Deleted\",kind=~\"Kustomization|HelmRelease\"})"
    }
   ]
  },
  {
   "title": "Failing Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gotk_reconcile_condition{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",type=\"Ready\",status=\"False\",kind=~\"Kustomization|HelmRelease\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Manifests Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_reconcile_condition{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",type=\"Ready\",status=\"True\",kind=~\"GitRepository|HelmRepository|Bucket\"})\n-\nsum(gotk_reconcile_condition{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",type=\"Ready\",status=\"Deleted\",kind=~\"GitRepository|HelmRepository|Bucket\"})"
    }
   ]
  },
  {
   "title": "Failing Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gotk_reconcile_condition{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",type=\"Ready\",status=\"False\",kind=~\"GitRepository|HelmRepository|Bucket\"})"
    }
   ]
  },
  {
   "title": "Reconciler ops avg. duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "  sum(rate(gotk_reconcile_duration_seconds_sum{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind)",
     "legendFormat": "{{`{{kind}}`}}"
    }
   ]
  },
  {
   "title": "Source ops avg. duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "  sum(rate(gotk_reconcile_duration_seconds_sum{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket\"}[5m])) by (kind)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket\"}[5m])) by (kind)",
     "legendFormat": "{{`{{kind}}`}}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cluster reconciliation readiness ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "gotk_reconcile_condition{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",type=\"Ready\",status=\"False\",kind=~\"Kustomization|HelmRelease\"}"
    }
   ]
  },
  {
   "title": "Source acquisition readiness ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "gotk_reconcile_condition{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",type=\"Ready\",status=\"False\",kind=~\"GitRepository|HelmRepository|Bucket\"}"
    }
   ]
  },
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Cluster reconciliation duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "  sum(rate(gotk_reconcile_duration_seconds_sum{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind, name)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind, name)",
     "legendFormat": "{{`{{kind}}/{{name}}`}}"
    }
   ]
  },
  {
   "title": "Source acquisition duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "  sum(rate(gotk_reconcile_duration_seconds_sum{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket\"}[5m])) by (kind, name)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket\"}[5m])) by (kind, name)",
     "legendFormat": "{{`{{kind}}/{{name}}`}}"
    }
   ]
  }
 ]
}
{
 "title": "Flux Control Plane",
 "tags": [ "flux" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(workqueue_queue_duration_seconds_count{pod!=\"\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(go_info{namespace=\"$namespace\",pod=~\".*-controller-.*\"})",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Max Work Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(workqueue_longest_running_processor_seconds{namespace=\"$namespace\",pod=~\".*-controller-.*\"})",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{namespace=\"$namespace\",pod=~\".*-controller-.*\"})"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",pod=~\".*-controller-.*\"}[1m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Kubernetes API Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",code!~\"2..\"}[1m]))",
     "legendFormat": "errors"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"$namespace\",pod=~\".*-controller-.*\"}[1m])",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\",pod=~\".*-controller-.*\"}[1m])",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  { "title": "Reconciliation Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Cluster Reconciliation Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds{name=\"kustomization\"}",
     "legendFormat": "kustomizations"
    }
   ]
  },
  {
   "title": "Cluster Reconciliations ops/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"kustomization\",result!=\"error\"}[1m])) by (controller)",
     "legendFormat": "successful reconciliations "
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"kustomization\",result=\"error\"}[1m])) by (controller)",
     "legendFormat": "failed reconciliations "
    }
   ]
  },
  {
   "title": "Git Sources ops/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"gitrepository\",result!=\"error\"}[1m]))",
     "legendFormat": "successful git pulls"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"gitrepository\",result=\"error\"}[1m]))",
     "legendFormat": "failed git pulls"
    }
   ]
  },
  { "title": "Helm Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Helm Release Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"helmrelease\"}[5m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Helm Releases ops/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"helmrelease\",result!=\"error\"}[1m])) by (controller)",
     "legendFormat": "successful reconciliations "
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"helmrelease\",result=\"error\"}[1m])) by (controller)",
     "legendFormat": "failed reconciliations "
    }
   ]
  },
  {
   "title": "Helm Charts ops/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"helmchart\",result!=\"error\"}[1m])) by (controller)",
     "legendFormat": "successful chart pulls"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"helmchart\",result=\"error\"}[1m])) by (controller)",
     "legendFormat": "failed chart pulls"
    }
   ]
  }
 ]
}
{
 "title": "Flux Applications",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(gotk_reconcile_condition, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Applications",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gotk_reconcile_condition{kind=~\"Kustomization|HelmRelease\",status=\"True\",namespace=\"$namespace\"}"
    },
    {
     "expr": "gotk_suspend_status{kind=~\"Kustomization|HelmRelease\",namespace=\"$namespace\"}"
    },
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{kind=~\"Kustomization|HelmRelease\",namespace=\"$namespace\"}[5m])) by (kind, name)\n/\nsum(rate(gotk_reconcile_duration_seconds_count{kind=~\"Kustomization|HelmRelease\",namespace=\"$namespace\"}[5m])) by (kind, name)"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "gotk_reconcile_condition{kind=~\"GitRepository|HelmChart\",status=\"True\",namespace=\"$namespace\"}"
    },
    {
     "expr": "gotk_suspend_status{kind=~\"GitRepository|HelmChart\",namespace=\"$namespace\"}"
    },
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{kind=~\"GitRepository|HelmChart\",namespace=\"$namespace\"}[5m])) by (kind, name)\n/\nsum(rate(gotk_reconcile_duration_seconds_count{kind=~\"GitRepository|HelmChart\",namespace=\"$namespace\"}[5m])) by (kind, name)"
    }
   ]
  },
  {
   "title": "Image Automation",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "gotk_reconcile_condition{kind=~\"ImageUpdateAutomation|ImageRepository\",status=\"True\",namespace=\"$namespace\"}"
    },
    {
     "expr": "gotk_suspend_status{kind=~\"ImageUpdateAutomation|ImageRepository\",namespace=\"$namespace\"}"
    },
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{kind=~\"ImageUpdateAutomation|ImageRepository\",namespace=\"$namespace\"}[5m])) by (kind, name)\n/\nsum(rate(gotk_reconcile_duration_seconds_count{kind=~\"ImageUpdateAutomation|ImageRepository\",namespace=\"$namespace\"}[5m])) by (kind, name)"
    }
   ]
  }
 ]
}
{
 "title": "Flux Engine",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(workqueue_queue_duration_seconds_count{pod!=\"\"}, namespace)"
    }
   },
   {
    "name": "workers",
    "query": {
     "query": "label_values(workqueue_queue_duration_seconds_count{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "workers" },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$workers.*\"}[5m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{pod=~\"$workers.*\"}[5m]))",
     "legendFormat": "Throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"$workers.*\",image!=\"\",container!=\"\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Work Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_queue_duration_seconds_sum{pod=~\"$workers.*\"}[5m])) / sum(rate(workqueue_queue_duration_seconds_count{pod=~\"$workers.*\"}[5m]))",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}