metallb:
  prometheus:
    # Set the prometheus namespace if podMonitor is enabled
    namespace: ""
    podMonitor:
      enabled: false
    prometheusRule:
      enabled: false
  configInline:
    address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 172.19.0.0/24
