{{- $labels := (include "external-secrets-config.labels" .) -}}
{{- range $key, $store := .Values.clusterSecretStores }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $key }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  {{- toYaml $store | nindent 2 }}
---
{{- end -}}
